'use client';
import {useEffect,useMemo,useState} from 'react';
import {Upload,FileText,Image as ImageIcon,CheckCircle2,ShieldCheck} from 'lucide-react';
const defaultPricing={bw:2,color:10,photo:10,pdf:2};
type FileItem={name:string,size:number};
export default function Home(){const [files,setFiles]=useState<FileItem[]>([]);const [service,setService]=useState<'bw'|'color'|'photo'|'pdf'>('bw');const [copies,setCopies]=useState(1);const [pages,setPages]=useState(1);const [submitted,setSubmitted]=useState<string|null>(null);const [accent,setAccent]=useState('#7c4dff');useEffect(()=>{document.documentElement.style.setProperty('--accent',accent)},[accent]);
const price=useMemo(()=>{const unit=defaultPricing[service];return service==='photo'?unit*copies:unit*pages},[service,copies,pages]);
function pick(list:FileList|null){if(!list)return;setFiles(Array.from(list).map(f=>({name:f.name,size:f.size})))}
function submit(){if(!files.length)return;setSubmitted(String(Math.floor(1000+Math.random()*9000)))}
return <main className="wrap"><nav className="nav"><div className="brand">Print<span>PIN</span></div><a href="/admin" className="btn secondary">Shop Admin</a></nav>{submitted?<section className="card" style={{textAlign:'center',padding:40}}><CheckCircle2 size={52} color="var(--success)"/><h2>Order Submitted</h2><p className="muted">Show this PIN to the shop owner.</p><div className="pin">{submitted}</div><p className="small">Estimated total: ₹{price.toFixed(2)}</p></section>:<><section className="hero"><p className="muted">FAST • SIMPLE • PRIVATE</p><h1>Print from your phone.</h1><p className="muted">Upload photos, PDFs or documents. Get a PIN. The shop confirms and prints.</p></section><div className="grid grid2" style={{marginTop:16}}><section className="card"><h2>1. Choose service</h2><div className="grid" style={{marginTop:12}}>{[['bw','B/W Print','₹2 / page'],['color','Color Print','₹10 / page'],['photo','Photo Print','₹10 / copy'],['pdf','PDF Print','₹2 / page']].map(([id,title,sub])=><button key={id} className={'service '+(service===id?'active':'')} onClick={()=>setService(id as any)}><b>{title}</b><div className="muted small">{sub}</div></button>)}</div></section><section className="card"><h2>2. Upload files</h2><label className="drop" style={{display:'block',marginTop:12}}><Upload size={28}/><b>Tap to select files</b><div className="muted small">Images, PDF and documents</div><input type="file" multiple accept="image/*,.pdf,.doc,.docx" onChange={e=>pick(e.target.files)}/></label>{files.length>0&&<div className="list" style={{marginTop:12}}>{files.map((f,i)=><div className="row" key={i}><FileText size={18}/><span style={{flex:1}}>{f.name}</span><span className="muted small">{(f.size/1024).toFixed(0)} KB</span></div>)}</div>}</section></div><section className="card" style={{marginTop:16}}><h2>3. Print options</h2><div className="grid grid2"><div><label className="label">Pages</label><input className="field" type="number" min="1" value={pages} onChange={e=>setPages(Math.max(1,+e.target.value||1))}/></div><div><label className="label">Copies</label><input className="field" type="number" min="1" value={copies} onChange={e=>setCopies(Math.max(1,+e.target.value||1))}/></div></div><div className="row" style={{justifyContent:'space-between',marginTop:20}}><div><div className="muted small">Estimated total</div><div className="price">₹{price.toFixed(2)}</div></div><button className="btn" disabled={!files.length} onClick={submit}>Generate PIN →</button></div></section><section className="card" style={{marginTop:16}}><div className="row"><ShieldCheck size={20}/><b>Your order PIN identifies your files at the shop.</b></div></section></>}<footer className="footer">PrintPIN • Light theme only • <a href="/admin">Admin Panel</a></footer></main>}
